name: my_music_player
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  on_audio_query: ^2.6.0
  just_audio: ^0.9.20
  get: ^4.6.1
  sqflite: ^2.0.2
  path: ^1.8.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.20
  share_plus: ^4.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
        - assets/images/

  fonts:
    - family: Samir
      fonts:
        - asset: assets/fonts/Heebo.ttf
