name: my_music_player
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  on_audio_query: ^2.6.0
  just_audio: ^0.9.20
  marquee: ^2.2.1
  get: ^4.6.1
  sqflite: ^2.0.2
  path: ^1.8.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Samir
      fonts:
        - asset: assets/fonts/Heebo.ttf
